### ISSUE TITLE
Uninitialized value $setpoint

### ISSUE THREAD

**Issue by llucax** [Juerd/eq3-max#9] opened 2020-02-07 14:35 UTC
I'm getting these warnings when running `max`:
```
Use of uninitialized value $setpoint in bitwise and (&) at /home/luca/software/eq3-max/bin/../lib/Max.pm line 125, <GEN2> line 8.
Use of uninitialized value $setpoint in bitwise and (&) at /home/luca/software/eq3-max/bin/../lib/Max.pm line 126, <GEN2> line 8.
Use of uninitialized value $setpoint in bitwise and (&) at /home/luca/software/eq3-max/bin/../lib/Max.pm line 125, <GEN2> line 8.
Use of uninitialized value $setpoint in bitwise and (&) at /home/luca/software/eq3-max/bin/../lib/Max.pm line 126, <GEN2> line 8.
```

Using current master (2a465957996d0a4f6df8767eb7befa85cec42cfa) on a Debian testing box.

**Comment by Juerd** [comment] 2020-02-07 15:18
Thanks for reporting the bug! This seems to be a duplicate of #5.

**Closed by Juerd** 2020-02-07 15:18 UTC

**Comment by llucax** [comment] 2020-02-07 20:18
Ah, yeah, I do have an Eco Button. The fix seems to work, thanks!
